name       : pugixml
version    : 1.8.1
release    : 4
source     :
    - https://github.com/zeux/pugixml/releases/download/v1.8.1/pugixml-1.8.1.tar.gz : 00d974a1308e85ca0677a981adc1b2855cb060923181053fb0abf4e2f37b8f39
license    : MIT
component  : system.utils
summary    : pugixml is a C++ XML processing library
description: |
    pugixml is a C++ XML processing library, which consists of a DOM-like interface with rich traversal/modification capabilities, an extremely fast XML parser which constructs the DOM tree from an XML file/buffer, and an XPath 1.0 implementation for complex data-driven tree queries. Full Unicode support is also available, with Unicode interface variants and conversions between different Unicode encodings (which happen automatically during parsing/saving).
builddeps  :
    - git
setup      : |
    sed -i 's/\/\/ #define PUGIXML_HAS_LONG_LONG/\#define PUGIXML_HAS_LONG_LONG/g' src/pugiconfig.hpp

    mkdir build && cd build
    %cmake -DBUILD_SHARED_LIBS=ON \
        ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    install -D -m00644 contrib/* -t $installdir/usr/include/pugixml/contrib/
