name       : pugixml
version    : 1.6
release    : 2
source     :
    - https://github.com/zeux/pugixml/archive/v1.6.tar.gz : 915b7723a08cd149e7f4475a7e4083eb131716175f5296f4e05938acd266eb33
license    : MIT
summary    : pugixml is a C++ XML processing library
description: |
    pugixml is a C++ XML processing library, which consists of a DOM-like interface with rich traversal/modification capabilities, an extremely fast XML parser which constructs the DOM tree from an XML file/buffer, and an XPath 1.0 implementation for complex data-driven tree queries. Full Unicode support is also available, with Unicode interface variants and conversions between different Unicode encodings (which happen automatically during parsing/saving).
builddeps  :
    - git
setup      : |
    sed -i 's/\/\/ #define PUGIXML_HAS_LONG_LONG/\#define PUGIXML_HAS_LONG_LONG/g' src/pugiconfig.hpp
    mkdir build
    cd build
    %cmake -DBUILD_SHARED_LIBS=ON ../scripts/
build      : |
    cd build
    %make 
install    : |
    cd build
    %make_install
